In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Load the dataset 
df=pd.read_csv('F:\Shopper Spectrum\online_retail.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\PRATHAP\AppData\Local\Temp\ipykernel_18560\1224482911.py:1: SyntaxWarning: invalid escape sequence '\S'
  df=pd.read_csv('F:\Shopper Spectrum\online_retail.csv')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSpend
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2022-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2022-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [52]:
df.shape

(541909, 8)

In [ ]:
# Display basic information about the columns and data typesdf.info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 69.3 MB

In [ ]:
# Check for missing values in each column
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
# change date column to right datetime format: 
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [ ]:
# Drop rows where CustomerID is null
df = df.dropna(subset=['CustomerID'])

# Remove canceled orders (Invoice starts with 'C')
# We convert to string first to make sure string methods work safely
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

# Filter out negative or zero Quantities and UnitPrices
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

In [ ]:
# Calculate Total Spend for each row
df['TotalSpend'] = df['Quantity'] * df['UnitPrice']

In [58]:
print("True Cleaned Data Shape:", df.shape)
print("Number of Unique Customers:", df['CustomerID'].nunique())

True Cleaned Data Shape: (397884, 9)
Number of Unique Customers: 4338

In [25]:
#find which product sells the most:
print(f"most selling prodcut: {df['Description'].value_counts().head(1)}")
print("============================")
print(f"lowest selling prodcut: {df['Description'].value_counts().tail(3)}")

most selling prodcut: Description
WHITE HANGING HEART T-LIGHT HOLDER    2016
Name: count, dtype: int64
============================
lowest selling prodcut: Description
LETTER "W" BLING KEY RING      1
LETTER "Z" BLING KEY RING      1
PAPER CRAFT , LITTLE BIRDIE    1
Name: count, dtype: int64

In [80]:
df.info()

<class 'pandas.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  str
 1   StockCode    392692 non-null  str
 2   Description  392692 non-null  str
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[us]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      392692 non-null  str
 8   TotalSpend   392692 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 49.2 MB

In [ ]:
# find no ofduplicates:
df.duplicated().sum()

np.int64(5192)

In [ ]:
# drop duplicates:
df=df.drop_duplicates()

In [72]:
df.duplicated().sum()

np.int64(0)

In [82]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSpend
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2022-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2022-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2022-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [83]:
df.to_csv('online_retail.csv',index=False)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 392692 entries, 0 to 392691
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  int64
 1   StockCode    392692 non-null  str
 2   Description  392692 non-null  str
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  str
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      392692 non-null  str
 8   TotalSpend   392692 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 50.9 MB